### ISSUE TITLE
Bind9 logging cause the service failed to start

### ISSUE THREAD

**Issue by ken-ywk** [corporate-gadfly/Tunlr-Clone#34]
I realize that when I input the logging part below, the bind9 will failed to start

logging {
    channel bind_log {
        file "/var/log/named/named.log" versions 5 size 30m;
        severity info;
        print-time yes;
        print-severity yes;
        print-category yes;
    };
    category default { bind_log; };
    category queries { bind_log; };
};

This is the output from /var/log/syslog

Feb 23 09:41:29 kenywk named[4862]: isc_stdio_open '/var/log/named/named.log' failed: file not found
Feb 23 09:41:29 kenywk named[4862]: configuring logging: file not found
Feb 23 09:41:29 kenywk named[4862]: loading configuration: file not found
Feb 23 09:41:29 kenywk named[4862]: exiting (due to fatal error)

in /var/log, I cant find the directory "named" too.

**Comment by abbypan** [comment]
thanks to  corporate-gadfly, :)
