### ISSUE TITLE
Adding domains - to BIND and sniproxy.conf?

### ISSUE THREAD

**Issue by steveharman** [corporate-gadfly/Tunlr-Clone#52]
Hello!

I thought I'd finally understood everything in the setup instructions but am confusrd on one last part.

I don't understand why the list of domains shown in the bind override config doesn't match those in the sniproxy conf.  I'd have tjought they needed to be the same?

The config instructions note "When you discover a new domain that you want to "master", simply add it to the zones.override file and restart bind9".   But don't we have to add new domains to the sniproxy conf file as well?

Many thanks,

Steve

**Comment by corporate-gadfly** [comment]
Yes that is the case. They should match.

**Comment by steveharman** [comment]
Thanks for the clarification - to avoid future confusion is it worth updating the setup instructions (unless I've misread them)?  

The sniproxy.conf table stanza at https://github.com/corporate-gadfly/Tunlr-Clone only shows 5 entries:

table {
    (hulu|huluim)\.com *
    abc\.(go\.)?com *
    (nbc|nbcuni)\.com *
    netflix\.com *
    ip2location\.com *
}

...whereas the the bind override conf shows 12:

zone "hulu.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "huluim.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "netflix.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "abc.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "abc.go.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "fox.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "link.theplatform.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "nbc.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "nbcuni.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "pandora.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "broadband.espn.go.com." {
    type master;
    file "/etc/bind/db.override";
};
zone "ip2location.com." {
    type master;
    file "/etc/bind/db.override";
};

Thanks again for the reply.

Steve
