### ISSUE TITLE
support different regions?

### ISSUE THREAD

**Issue by chovy** [corporate-gadfly/Tunlr-Clone#53]
There are some US-services where I need a US-based IP, and others that are US-based that I need a foreign IP to avoid blackouts...for example FOX Sports streams will only play from a US-ip....but MLB.tv will blackout local games and playoffs if my IP is US-based.

Is there anyway to route different domains through different VPS's in the appropriate country?

**Comment by HalfEatenPie** [comment]
Setup the SNI Proxy on different servers around the USA then and then use a local DNS server to determine when to proxy through different servers.

**Comment by chovy** [comment]
Got it working. thanks.
